name: todo_list_app
description: "Flutter Technical Case"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #StateManagement
  flutter_bloc:

  #Core
  fpdart:
  freezed_annotation:
  json_annotation:
  fast_immutable_collections:

  #DI
  get_it:
  injectable:

  #LocalStorage
  get_storage:
  flutter_secure_storage:

  #Notifications
  flutter_local_notifications:

  #UI
  flutter_form_builder:
  form_builder_validators:
  flex_color_scheme:
  flutter_native_splash:
  timezone:

  #Routing
  go_router:

  #Network
  dio:
  pretty_dio_logger:


dev_dependencies:

  flutter_test:
    sdk: flutter
  injectable_generator:

  flutter_launcher_icons:
  build_runner:
  json_serializable:
  freezed:
  very_good_analysis:
  flutter_lints:
  mocktail:
  bloc_test:
flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/themes/
    - assets/icons/
